// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

/** True when this build has non-empty Supabase URL + anon key (still may be wrong URL). */
export const isSupabaseClientConfigured = Boolean(
  SUPABASE_URL?.trim() && SUPABASE_PUBLISHABLE_KEY?.trim()
);

/** Host baked into this build (for troubleshooting "cannot reach server"). */
export function getSupabaseBuildHost(): string {
  if (!SUPABASE_URL?.trim()) return "(empty — VITE_SUPABASE_URL not set at build time)";
  try {
    return new URL(SUPABASE_URL).hostname;
  } catch {
    return "(invalid VITE_SUPABASE_URL)";
  }
}

/** Shown when fetch fails (wrong URL → ERR_NAME_NOT_RESOLVED, missing env, etc.) */
export const SUPABASE_CONNECTIVITY_HINT =
  "Cannot reach server. Check Vercel env vars and redeploy: set VITE_SUPABASE_URL (https://YOUR_REF.supabase.co) and VITE_SUPABASE_PUBLISHABLE_KEY from Supabase → Project Settings → API. They must match the project where your database lives. Redeploy after saving—Vite bakes env in at build time. If the URL is wrong you’ll see ERR_NAME_NOT_RESOLVED in the browser Network tab.";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    "Missing Supabase env vars. Add VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in Vercel → Settings → Environment Variables, then redeploy."
  );
} else if (typeof window !== "undefined") {
  try {
    const host = new URL(SUPABASE_URL).hostname;
    if (!host.endsWith(".supabase.co")) {
      console.warn("[Supabase] VITE_SUPABASE_URL host should be *.supabase.co, got:", host);
    } else {
      console.info("[Supabase] Using host:", host);
    }
  } catch {
    console.error("[Supabase] Invalid VITE_SUPABASE_URL:", SUPABASE_URL);
  }
}

function mergeAbortSignals(signals: AbortSignal[]): AbortSignal {
  const combined = new AbortController();
  const onAbort = () => combined.abort();
  for (const s of signals) {
    if (s.aborted) {
      combined.abort();
      return combined.signal;
    }
    s.addEventListener("abort", onAbort, { once: true });
  }
  return combined.signal;
}

/**
 * Hard deadlines per request class so a hung TCP refresh cannot wedge every button after idle
 * (GoTrue runs token refresh inside a lock; one stuck `/auth/v1/token` blocks getSession & REST).
 * Auth-js JWKS cache TTL is 10m — stalls around that time often trace to unbounded fetch waits.
 */
function supabaseFetch(url: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const href =
    typeof url === "string"
      ? url
      : url instanceof Request
        ? url.url
        : url.href;
  const headers = new Headers(init?.headers);
  // Edge Functions reject the browser preflight if these extra headers are not allow-listed.
  if (!href.includes("/functions/v1/")) {
    headers.set("Cache-Control", "no-cache");
    headers.set("Pragma", "no-cache");
  }

  let deadlineMs = 55_000;
  if (href.includes("/auth/v1/")) {
    deadlineMs = 28_000;
  } else if (href.includes("/storage/v1/object/") && (init?.method === "POST" || init?.method === "PUT")) {
    deadlineMs = 120_000;
  } else if (href.includes("/functions/v1/")) {
    deadlineMs = 185_000;
  }

  const timeoutCtl = new AbortController();
  const timer = globalThis.setTimeout(() => timeoutCtl.abort(), deadlineMs);
  const nextSignal =
    init?.signal != null ? mergeAbortSignals([init.signal, timeoutCtl.signal]) : timeoutCtl.signal;

  return fetch(url, { ...init, headers, cache: "no-store", signal: nextSignal }).finally(() =>
    globalThis.clearTimeout(timer)
  );
}

// Bypass navigator.locks — can deadlock and cause getSession to hang indefinitely
const noopLock = async <R>(_name: string, _acquireTimeout: number, fn: () => Promise<R>) => fn();

export const supabase = createClient<Database>(SUPABASE_URL || "", SUPABASE_PUBLISHABLE_KEY || "", {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    lock: noopLock,
  },
  global: {
    fetch: supabaseFetch,
  },
});